### PR TITLE
closes #183 Plugin not working with multiple SCM configuration

### LINKED ISSUE #183: Plugin not working with multiple SCM configuration.
Hey,
I'm using this plugin:
https://wiki.jenkins-ci.org/display/JENKINS/Multiple+SCMs+Plugin

I have 4 repositories configured in one job. The first one is checking out properly, but problem starts with other ones. I guess gitlab webhook is sending commit hash from one repository only and tries to use it with all of them. This is the error message:
13:31:36 FATAL: Command "git rev-parse 9f3840b5f10bd7e9d4a7bde849aad96e9926d827^{commit}" returned status code 128:
13:31:36 stdout: 9f3840b5f10bd7e9d4a7bde849aad96e9926d827^{commit}
13:31:36 
13:31:36 stderr: fatal: ambiguous argument '9f3840b5f10bd7e9d4a7bde849aad96e9926d827^{commit}': unknown revision or path not in the working tree.
13:31:36 Use '--' to separate paths from revisions, like this:
13:31:36 'git <command> [<revision>...] -- [<file>...]'

Is there a way to fix it?
Regards
skyline00

### PR DESCRIPTION
**Pull request by froque**
(and duplicated #187)

See https://issues.jenkins-ci.org/browse/JENKINS-26587 and https://github.com/jenkinsci/git-plugin/pull/296
for more information

### CODE REVIEW

File: src/main/java/com/dabsquared/gitlabjenkins/GitLabPushTrigger.java [hunk 1]
```diff
@@ -323,8 +324,19 @@ private GitLabPushCause createGitLabPushCause(GitLabPushRequest req) {
     public RevisionParameterAction createPushRequestRevisionParameter(Job<?, ?> job, GitLabPushRequest req) {
         RevisionParameterAction revision = null;
 
+
+        // add url to remote to work with multiple scm plugin.
```
Comment (coder-hugo) [inline src/main/java/com/dabsquared/gitlabjenkins/GitLabPushTrigger.java]: I don't like comments in the code. I get this information also using git blame or the corresponding functionality of an IDE. Comments are bad as they usually aren't touched during refactorings. Which end in comments that tell something about the following code which isn't the truth.
IMO the reason for adding some new code has to be described in the commit message not with a comment within the code.
